FROM {{ user }}/mesos-base:latest

RUN curl -fLsS https://get.docker.com/ | sh

ENV MESOS_CONTAINERIZERS docker,mesos

# https://mesosphere.github.io/marathon/docs/native-docker.html
ENV MESOS_EXECUTOR_REGISTRATION_TIMEOUT 5mins

ENV MESOS_WORK_DIR /data

VOLUME /data

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
