FROM {{ user }}/mesos-base:latest

RUN \
  curl -L https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 -o /usr/bin/docker && \
  chmod +x /usr/bin/docker

ENV MESOS_CONTAINERIZERS docker,mesos

# https://mesosphere.github.io/marathon/docs/native-docker.html
ENV MESOS_EXECUTOR_REGISTRATION_TIMEOUT 5mins

ENV MESOS_WORK_DIR /data

VOLUME /data

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
