{% if 'ubuntu' in version %}
FROM ubuntu:14.04

RUN echo "deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" > /etc/apt/sources.list.d/openjdk.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv 86F44E2A && \
  apt-get update && \
  apt-get -y install openjdk-8-jre-headless && \
  rm -rf /var/lib/apt/lists/*

# FIXME v0.24.1
RUN echo "deb http://repos.mesosphere.io/ubuntu/ trusty main" > /etc/apt/sources.list.d/mesosphere.list && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF && \
  apt-get -y update && \
  apt-get -y install mesos=0.25.0-0.2.70.ubuntu1404 && \
  rm -rf /var/lib/apt/lists/*

RUN \
  apt-get -y update && \
  apt-get install -y curl
{% endif %}

{% if type == 'scheduler' %}
RUN \
  cd / && \
  curl -LO https://github.com/mesos/elasticsearch/releases/download/1.0.1/mesos-elasticsearch-scheduler-1.0.1.jar
{% endif %}

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
