FROM {{ user }}/mesos-base:{{ version }}

{% if type == 'slave' %}
RUN curl -fLsS https://get.docker.com/ | sh

ENV MESOS_CONTAINERIZERS docker,mesos

# https://mesosphere.github.io/marathon/docs/native-docker.html
ENV MESOS_EXECUTOR_REGISTRATION_TIMEOUT 5mins
{% endif %}

ENV MESOS_WORK_DIR /data

VOLUME /data

ADD {{ entrypoint }} /

ENTRYPOINT ["/{{ entrypoint }}"]
