FROM {{ user }}/mesos-base:latest

ENV MARATHON_VERSION 1.1.0-RC1

RUN \
  curl -L http://downloads.mesosphere.com/marathon/v$MARATHON_VERSION/marathon-$MARATHON_VERSION.tgz | tar xzf - && \
  mv marathon-$MARATHON_VERSION/target/scala-2.11/marathon-assembly-$MARATHON_VERSION.jar /marathon.jar && \
  rm -rf marathon-$MARATHON_VERSION

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
