FROM {{ user }}/mesos-base:latest

ENV VERSION 1.1.0-RC1

RUN \
  curl -L http://downloads.mesosphere.com/marathon/v$VERSION/marathon-$VERSION.tgz | tar xzf - && \
  mv marathon-$VERSION/target/scala-2.11/marathon-assembly-$VERSION.jar /marathon.jar && \
  rm -rf marathon-$VERSION

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
