{% if 'centos' in version %}
FROM {{ user }}/mesos-base:0.24.1-centos-7

RUN yum -y install marathon-1.1.1-1.0.472.el7
{% elif 'ubuntu-15.04' in version %}
FROM {{ user }}/mesos-base:0.24.1-ubuntu-15.04

RUN \
  apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF && \
  echo deb http://repos.mesosphere.io/ubuntu vivid main > /etc/apt/sources.list.d/mesosphere.list && \
  apt-get update && \
  apt-get -y install marathon=1.1.1-1.0.472.ubuntu1504
{% endif %}

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
