FROM {{ user }}/mesos-base:latest

ENV VERSION 2.4.0-RC1

RUN \
  curl -L https://github.com/mesos/chronos/releases/download/$VERSION/chronos-$VERSION.tgz | tar xzf - && \
  mv chronos-$VERSION/target/chronos-$VERSION.jar /chronos.jar && \
  rm -rf chronos-$VERSION

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
