{% if 'centos' in version %}
FROM {{ user }}/mesos-base:0.24.1-centos-7

RUN yum -y install chronos-2.4.0-0.1.20151007110204.el7
{% elif 'ubuntu' in version %}
FROM {{ user }}/mesos-base:0.24.1-ubuntu-14.04

RUN \
  apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF && \
  echo deb http://repos.mesosphere.io/ubuntu trusty main > /etc/apt/sources.list.d/mesosphere.list && \
  apt-get update && \
  apt-get -y install chronos=2.4.0-0.1.20151007110204.ubuntu1404
{% endif %}

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
